
import time
import os
import sys
from pathlib import Path

sys.path.append(str(Path(os.path.dirname(os.path.abspath(__file__))).parent.parent))
from src.retriever.factory import get_retriever
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from src.prompt import template
from langchain_core.runnables import RunnableLambda
from src.utils.logger import get_logger
logger = get_logger()
from langfuse.decorators import observe, langfuse_context  
from langfuse.callback import CallbackHandler                  
from langfuse import Langfuse                                  
langfuse_handler = CallbackHandler()
langfuse = Langfuse()

class RAGChain:
    def __init__(self, config: dict):
        """
        Initialize retriever, prompt template, and LLM.
        """
  
        self.retriever = get_retriever(config)
        logger.info("Retriever initialized.")

        self.prompt = ChatPromptTemplate.from_template(template)
        logger.info("Prompt template initialized.")

        llm_cfg = config["llm"]
        self.llm = ChatOpenAI(
            temperature=llm_cfg["temperature"],
            model_name=llm_cfg["model"]
        )
        logger.info(
            f"LLM initialized with model={llm_cfg['model']}, temp={llm_cfg['temperature']}"
        )

        # Placeholder for the last trace ID
        self.last_trace_id: str | None = None

    @observe() 
    def answer_question(self, query: str) -> str:
        """
        Retrieve docs, invoke LLM, parse response, and capture trace_id.
        """
        # Build a small LangChain runnable for RAG
        rag_chain = (
            {
                "context": RunnableLambda(
                    lambda q: "\n\n".join(
                        doc.page_content for doc in self.retriever.get_relevant_documents(q)
                    )
                ),
                "question": RunnablePassthrough()
            }
            | self.prompt
            | self.llm
            | StrOutputParser()
        )

        # Invoke with Langfuse callback
        response = rag_chain.invoke(
            query,
            config={
                "callbacks": [langfuse_handler],
                "run_name": "xpanse_escrow_query"
            }
        )

        # Capture the autogenerated trace ID 
        try:
            self.last_trace_id = langfuse_handler.get_trace_id()
            logger.info(f"Captured trace_id={self.last_trace_id}")
        except Exception as e:
            logger.exception("Unable to retrieve Langfuse trace_id")

        return response

    def retrieve_documents(self, query: str) -> list:
        """
        (Optional) Lower-level retrieval method if you need it elsewhere.
        """
        start = time.time()
        docs = self.retriever.get_relevant_documents(query)
        elapsed = time.time() - start
        logger.info(f"Retrieved {len(docs)} docs in {elapsed:.2f}s")
        return docs

    def submit_score(self, value: float, comment: str = "") -> None:
        """
        Attach a user feedback score to the last recorded Langfuse trace.
        """
        if not self.last_trace_id:
            logger.warning("No trace_id available; cannot submit score.")
            return

        try:
            
            langfuse.score(
                trace_id=self.last_trace_id,
                name="user-feedback",
                value=value,
                comment=comment
            )
            logger.info(f"Submitted score={value} for trace {self.last_trace_id}")
        except Exception:
            logger.exception(f"Failed to submit score for trace {self.last_trace_id}")

